### PR TITLE
Added compatibility for osx

### PR DESCRIPTION
**Pull request by vito-c**
Added compatibility for osx

### CODE REVIEW

**Comment by shramov** [comment]
Can you verify that wip-osx branch is building or osx?
I've merged your commits but with some cleanup - squashed them and changed shell if/else to makefile counterparts

**Comment by vito-c** [comment]
ok I pulled your changes into my branch and ran into a small issue. OSX clang uses a comma for -Wl,-install_name,libjson2pb.so vs Linux -Wl,-install_name=libjson2pb.so

**Comment by vito-c** [comment]
I fixed the issue and pushed to this repo

**Comment by shramov** [comment]
Maybe it's better to use -Wl,-install_name -Wl,$@ ?

**Comment by vito-c** [comment]
did you still me to test again?

**Pull request closed without merging**
